# Generated by Django 3.2.9 on 2021-12-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=18, unique=True)),
                ('Email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=30, null=True)),
                ('Country', models.CharField(default='', max_length=10, null=True)),
                ('State', models.CharField(default='', max_length=25, null=True)),
                ('City', models.CharField(default='', max_length=25, null=True)),
                ('Address', models.TextField(default='', max_length=150, null=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
