# Generated by Django 4.0.1 on 2022-01-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='', upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
