# Generated by Django 4.0.1 on 2022-01-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Master',
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=100, null=True)),
                ('subscribers', models.IntegerField(default=0, max_length=1000000000, null=True)),
                ('following', models.IntegerField(default=0, max_length=100000, null=True)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master')),
            ],
            options={
                'db_table': 'Channels',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='channels',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.channels'),
            preserve_default=False,
        ),
    ]
