# Generated by Django 4.0.1 on 2022-01-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_video_master_channels_video_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='catagory',
            field=models.CharField(default='general', max_length=100, null=True),
        ),
    ]
