# Generated by Django 4.0.1 on 2022-01-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_video_channels_video_channel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master')),
                ('subscribed_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channels')),
            ],
            options={
                'db_table': 'Subsciption',
            },
        ),
    ]
