# Generated by Django 4.0.1 on 2022-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_name',
            field=models.CharField(default='', max_length=100, null=True, unique=b'I01\n'),
        ),
    ]
