# Generated by Django 4.0.1 on 2022-01-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_channel_name_video_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='Master',
        ),
        migrations.AddField(
            model_name='channels',
            name='Profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
    ]
