# Generated by Django 4.0.1 on 2022-01-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_subscriptions_master_subscriptions_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_and_likes',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
    ]
