# Generated by Django 4.0.1 on 2022-01-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_comments_and_likes_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_and_likes',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.channels'),
        ),
    ]
